apiVersion: v1
kind: Service
metadata:
  name: nginx-external-lb
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      name: http
